version: '3'
services:
  web:
    image: robsdudeson/robsdudeson.com-nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
      - app1

  app:
    image: robsdudeson/robsdudeson.com:latest
    restart: always
    command: sh -c "wait-for-it db:5432 -- bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    expose:
      - "3000"
    links:
      - "db:dbhost"
    depends_on:
      - db

  app1:
    image: robsdudeson/rah-prototype:latest
    restart: always
    command: sh -c "wait-for-it db:5432 -- bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    expose:
      - "3001"
    links:
      - "db:dbhost"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
    expose:
      - "5432"

volumes:
  dbdata:
