FROM nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/sites-available/robsdudeson.com.conf /etc/nginx/sites-available/robsdudeson.com.conf
COPY nginx/sites-available/rentahero.us.conf /etc/nginx/sites-available/rentahero.us.conf
RUN mkdir /etc/nginx/sites-enabled
RUN ln -sf /etc/nginx/sites-available/robsdudeson.com.conf /etc/nginx/sites-enabled/robsdudeson.com.conf
RUN ln -sf /etc/nginx/sites-available/rentahero.us.conf /etc/nginx/sites-enabled/rentahero.us.conf

EXPOSE 80
